export const content = {
  tr: {
    about: {
      title: "Hakkımızda",
      p1: "ObsCloner, Obsessive Inc. bünyesinde geliştirilen, Discord topluluk yöneticilerinin ve sunucu sahiplerinin operasyonel yüklerini hafifletmeyi amaçlayan, sektörün en gelişmiş ve güvenilir sunucu kopyalama çözümüdür. 2026 yılında kurulan Obsessive Inc., Discord API ekosistemine yönelik inovatif otomasyon araçları geliştirmeye odaklanmış, kullanıcı deneyimini ve veri güvenliğini her zaman ön planda tutan bir teknoloji ekibidir.",
      p2: "Geliştirdiğimiz bu platform, sadece basit bir kopyalama aracı olmanın ötesinde, büyük ölçekli toplulukların sunucu yedekleme, felaket kurtarma ve sunucu taşıma ihtiyaçlarını tek bir tıkla çözebilmeleri için tasarlanmıştır. ObsCloner, binlerce kanalı, karmaşık rol hiyerarşilerini ve özel emojileri, Discord'un hız limitlerine (Rate Limit) takılmadan, akıllı gecikme algoritmalarıyla sorunsuz bir şekilde yeni sunuculara aktarabilir.",
      h2: "Neden ObsCloner'ı Seçmelisiniz?",
      li1: "Maksimum Hız ve Hassasiyet: Sektördeki en optimize klonlama motorunu kullanarak, kategoriler, metin/ses kanalları ve izin setlerini %100 doğrulukla taşır.",
      li2: "Uçtan Uca Güvenlik: Kullanıcı verileri bizim için kutsaldır. Tokenlarınız veya sunucu yapılandırmalarınız asla sunucularımızda saklanmaz; tüm işlemler tarayıcı üzerinden doğrudan Discord ile konuşur.",
      li3: "Gelişmiş Hata Yönetimi: İşlem sırasında oluşabilecek teknik aksaklıkları otomatik olarak algılar ve kaldığı yerden devam ederek sürecin tamamlanmasını garanti eder.",
      li4: "Global Destek: 7 farklı dilde sunduğumuz arayüz ve içeriklerle, dünya çapındaki topluluk yöneticilerine hitap ediyoruz."
    },
    privacy: {
      title: "Gizlilik Politikası",
      p1: "ObsCloner ekibi olarak kişisel verilerinizin gizliliği ve güvenliği en büyük önceliğimizdir. Bu gizlilik politikası, ObsCloner web sitesini ve araçlarını kullandığınızda bilgilerinizin nasıl toplandığını, kullanıldığını ve korunduğunu ayrıntılı olarak açıklamaktadır. Hizmetlerimizi kullanarak, bu politikada belirtilen veri uygulamalarını kabul etmiş sayılırsınız.",
      h2_1: "1. Veri İşleme ve Depolama Prensibi",
      p2: "ObsCloner, temel olarak bir 'client-side' (istemci tarafı) mimarisi üzerine inşa edilmiştir. Bu mimari gereği, uygulamaya girdiğiniz Discord kullanıcı tokenları, sunucu ID'leri, kanal yapılandırmaları veya diğer hassas meta veriler hiçbir şekilde Obsessive Inc. sunucularına iletilmez, kaydedilmez veya herhangi bir veritabanında depolanmaz. Tüm API çağrıları ve veri transferleri, doğrudan sizin yerel tarayıcınızdan Discord'un resmi API sunucularına şifreli bir kanal (HTTPS) üzerinden yapılır. Bu, verileriniz üzerinde tam kontrolün sizde kalmasını sağlar.",
      h2_2: "2. Günlük Verileri (Log Data) ve Analiz",
      p3: "Sitemizi ziyaret ettiğinizde, tarayıcının gönderdiği bilgileri otomatik olarak toplayabiliriz. Bu bilgiler; cihazınızın İnternet Protokolü (IP) adresi, tarayıcı türü, tarayıcı sürümü, ziyaret ettiğiniz sayfalarımız, ziyaretinizin saati ve tarihi, bu sayfalarda geçirilen süre ve diğer istatistiksel verileri içerebilir. Bu veriler tamamen anonimdir ve yalnızca web sitemizin performansını analiz etmek ve kullanıcı deneyimini iyileştirmek amacıyla kullanılır.",
      h2_3: "3. Çerez (Cookie) Politikası",
      p4: "ObsCloner, kullanıcı deneyimini optimize etmek için çerezleri kullanır. Çerezler, web siteleri tarafından cihazınıza bırakılan küçük veri dosyalarıdır. Bizim kullandığımız çerezler temel olarak teknik amaçlıdır; örneğin, seçtiğiniz dil tercihini (TR, EN, vb.) hatırlamak veya oturum sürekliliğini sağlamak için kullanılırlar. Tarayıcı ayarlarınızdan çerezleri reddedebilirsiniz ancak bu durumda sitemizin bazı fonksiyonlarının tam çalışmayabileceğini unutmamalısınız.",
      h2_4: "4. GDPR ve KVKK Uyumluluğu",
      p5: "Avrupa Birliği Genel Veri Koruma Yönetmeliği (GDPR) ve Kişisel Verilerin Korunması Kanunu (KVKK) ilkelerine saygı duyuyoruz. Kullanıcılarımızın verilerine erişim, düzeltme veya silme hakları saklıdır. Ancak sistemimiz hiçbir kişisel veriyi depolamadığı için, silinecek bir veri kaydı da bulunmamaktadır. Herhangi bir sorunuz olması durumunda support@aiobsessive.com adresi üzerinden bizimle iletişime geçebilirsiniz.",
      h2_5: "5. Üçüncü Taraf Bağlantıları",
      p6: "Hizmetimiz sırasında Discord Inc. API'leri kullanılmaktadır. Discord'un kendi gizlilik politikaları ve kullanım şartları bizim kontrolümüz dışındadır. Bu nedenle, Discord platformunun verilerinizi nasıl işlediğini anlamak için onların resmi dokümantasyonlarını incelemenizi öneririz.",
      h2_6: "6. Çocukların Gizliliği",
      p7: "Hizmetlerimiz 13 yaşın altındaki çocuklara hitap etmemektedir. Bilerek 13 yaşın altındaki çocuklardan kişisel bilgi toplamıyoruz. Bir çocuğun bize kişisel bilgi verdiğini fark edersek, bu bilgileri sunucularımızdan derhal sileriz."
    },
    terms: {
      title: "Kullanım Şartları",
      p1: "ObsCloner web sitesini ve beraberindeki araçları kullanarak, bu kullanım şartlarını, tüm ilgili yasaları ve düzenlemeleri kabul etmiş sayılırsınız. Bu şartların herhangi birini kabul etmiyorsanız, bu siteyi kullanmanız yasaktır.",
      h2_1: "1. Kullanım Lisansı ve Kısıtlamalar",
      p2: "ObsCloner, kullanıcıya Discord sunucularını yedeklemek ve taşımak amacıyla sınırlı, devredilemez ve kişisel bir kullanım lisansı sunar. Bu lisans kapsamında şunları yapamazsınız:\n- Yazılımı kopyalamak, değiştirmek veya tersine mühendislik işlemlerine tabi tutmak.\n- Yazılımı ticari bir amaçla veya kamuya açık bir gösterim için kullanmak.\n- Yazılım üzerindeki telif hakkı veya diğer mülkiyet kayıtlarını kaldırmak.\n- Yazılımı başka bir kişiye transfer etmek veya başka bir sunucuda 'yansıtmak' (mirror).",
      h2_2: "2. Sorumluluk Reddi (Disclaimer)",
      p3: "ObsCloner 'olduğu gibi' sunulmaktadır. Obsessive Inc., bu aracın kullanımıyla ilgili zımni veya açık hiçbir garanti vermez. Aracın, Discord Hizmet Şartları'na (ToS) aykırı şekilde kullanılması, başkalarının mülkiyetindeki sunucuların izinsiz kopyalanması veya hesabın Discord tarafından kısıtlanması durumunda tüm sorumluluk kullanıcıya aittir. Kullanıcının işlem sırasında yapacağı hatalardan (yanlış sunucu ID'si girmek, token paylaşmak vb.) doğacak zararlardan firmamız sorumlu tutulamaz.",
      h2_3: "3. Sorumluluğun Sınırlandırılması",
      p4: "Hiçbir durumda Obsessive Inc. veya tedarikçileri, ObsCloner'ın kullanımından veya kullanılamamasından kaynaklanan herhangi bir zarardan (veri kaybı, kar kaybı veya iş kesintisi dahil ancak bunlarla sınırlı olmamak üzere) sorumlu tutulamaz. Bazı yargı bölgeleri, zımni garantiler üzerindeki sınırlamalara veya dolaylı zararlar için sorumluluk sınırlamalarına izin vermediğinden, bu sınırlamalar sizin için geçerli olmayabilir.",
      h2_4: "4. Materyallerdeki Hatalar",
      p5: "Sitede görünen materyaller teknik, tipografik veya fotografik hatalar içerebilir. Obsessive Inc., sitesindeki materyallerin doğru, tam veya güncel olduğunu garanti etmez. Materyallerde önceden haber vermeksizin değişiklik yapabiliriz.",
      h2_5: "5. Şartların Değiştirilmesi",
      p6: "Obsessive Inc., web sitesi için bu kullanım şartlarını istediği zaman önceden haber vermeksizin revize edebilir. Bu web sitesini kullanarak, o anki güncel kullanım şartlarına bağlı kalmayı kabul etmiş sayılırsınız.",
      h2_6: "6. Uygulanacak Hukuk",
      p7: "ObsCloner ile ilgili her türlü talep, kanunlar ihtilafına bakılmaksızın yerel mahkemelerin yetkisine ve yasalarına tabi olacaktır."
    }
  },
  en: {
    about: {
      title: "About Us",
      p1: "ObsCloner is the industry's most advanced and reliable server copying solution developed under Obsessive Inc., aimed at easing the operational burdens of Discord community managers and server owners. Founded in 2026, Obsessive Inc. is a technology team focused on developing innovative automation tools for the Discord API ecosystem, always prioritizing user experience and data security.",
      p2: "This platform we've developed is more than just a simple copying tool; it's designed so that large-scale communities can solve their server backup, disaster recovery, and server migration needs with a single click. ObsCloner can seamlessly transfer thousands of channels, complex role hierarchies, and custom emojis to new servers without getting caught in Discord's rate limits, thanks to its smart delay algorithms.",
      h2: "Why Choose ObsCloner?",
      li1: "Maximum Speed and Precision: Using the most optimized cloning engine in the industry, it transfers categories, text/voice channels, and permission sets with 100% accuracy.",
      li2: "End-to-End Security: User data is sacred to us. Your tokens or server configurations are never stored on our servers; all operations speak directly with Discord via your browser.",
      li3: "Advanced Error Handling: It automatically detects technical glitches that may occur during the process and ensures completion by continuing from where it left off.",
      li4: "Global Support: We cater to community managers worldwide with interfaces and content offered in 7 different languages."
    },
    privacy: {
      title: "Privacy Policy",
      p1: "As the ObsCloner team, the privacy and security of your personal data are our top priority. This privacy policy explains in detail how your information is collected, used, and protected when you use the ObsCloner website and tools. By using our services, you consent to the data practices described in this policy.",
      h2_1: "1. Data Processing and Storage Principle",
      p2: "ObsCloner is fundamentally built on a 'client-side' architecture. Due to this architecture, Discord user tokens, server IDs, channel configurations, or other sensitive metadata you enter into the application are not transmitted to Obsessive Inc. servers, recorded, or stored in any database. All API calls and data transfers are made directly from your local browser to Discord's official API servers via an encrypted channel (HTTPS). This ensures that you maintain full control over your data.",
      h2_2: "2. Log Data and Analytics",
      p3: "When you visit our site, we may automatically collect information that your browser sends. This information may include your device's Internet Protocol (IP) address, browser type, browser version, our pages you visit, the time and date of your visit, the time spent on those pages, and other statistical data. This data is completely anonymous and is used only to analyze the performance of our website and improve the user experience.",
      h2_3: "3. Cookie Policy",
      p4: "ObsCloner uses cookies to optimize the user experience. Cookies are small data files placed on your device by websites. The cookies we use are primarily for technical purposes; for example, they are used to remember your preferred language choice (EN, TR, etc.) or to ensure session continuity. You can refuse cookies from your browser settings, but in this case, please note that some functions of our site may not work fully.",
      h2_4: "4. GDPR and Data Protection Compliance",
      p5: "We respect the principles of the European Union General Data Protection Regulation (GDPR). Our users reserve the right to access, correct, or delete their data. However, since our system does not store any personal data, there is no data record to be deleted. If you have any questions, you can contact us at support@aiobsessive.com.",
      h2_5: "5. Third-Party Links",
      p6: "Discord Inc. APIs are used during our service. Discord's own privacy policies and terms of use are beyond our control. Therefore, we recommend that you review their official documentation to understand how the Discord platform processes your data.",
      h2_6: "6. Children's Privacy",
      p7: "Our services do not address children under the age of 13. We do not knowingly collect personal information from children under 13. If we discover that a child has provided us with personal information, we immediately delete this information from our servers."
    },
    terms: {
      title: "Terms of Service",
      p1: "By accessing the ObsCloner website and accompanying tools, you agree to these terms of service, all applicable laws, and regulations. If you do not agree with any of these terms, you are prohibited from using this site.",
      h2_1: "1. License and Use Restrictions",
      p2: "ObsCloner grants the user a limited, non-transferable, and personal license to use the tool for the purpose of backing up and migrating Discord servers. Under this license, you may not:\n- Copy, modify, or reverse engineer the software.\n- Use the software for a commercial purpose or for any public display.\n- Remove any copyright or other proprietary notations from the software.\n- Transfer the software to another person or 'mirror' it on any other server.",
      h2_2: "2. Disclaimer",
      p3: "ObsCloner is provided 'as is'. Obsessive Inc. makes no warranties, expressed or implied, regarding the use of this tool. Any responsibility for using the tool in a manner contrary to Discord Terms of Service (ToS), unauthorized copying of servers owned by others, or account restrictions by Discord lies entirely with the user. Our company cannot be held responsible for damages arising from user errors (entering incorrect server ID, sharing tokens, etc.) during the process.",
      h2_3: "3. Limitation of Liability",
      p4: "In no event shall Obsessive Inc. or its suppliers be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption) arising out of the use or inability to use ObsCloner. Because some jurisdictions do not allow limitations on implied warranties, or limitations of liability for consequential or incidental damages, these limitations may not apply to you.",
      h2_4: "4. Accuracy of Materials",
      p5: "The materials appearing on the site could include technical, typographical, or photographic errors. Obsessive Inc. does not warrant that any of the materials on its website are accurate, complete, or current. We may make changes to the materials at any time without notice.",
      h2_5: "5. Modifications to Terms",
      p6: "Obsessive Inc. may revise these terms of service for its website at any time without notice. By using this website you are agreeing to be bound by the then current version of these terms of service.",
      h2_6: "6. Governing Law",
      p7: "Any claim relating to ObsCloner shall be governed by the laws of the local jurisdiction without regard to its conflict of law provisions."
    }
  },
  es: {
    about: {
      title: "Sobre Nosotros",
      p1: "ObsCloner es la solución de copia de servidores más avanzada y confiable de la industria desarrollada bajo Obsessive Inc., con el objetivo de aliviar las cargas operativas de los administradores de comunidades y propietarios de servidores de Discord. Fundada en 2026, Obsessive Inc. es un equipo tecnológico enfocado en desarrollar herramientas de automatización innovadoras para el ecosistema de la API de Discord, priorizando siempre la experiencia del usuario y la seguridad de los datos.",
      p2: "Esta plataforma que hemos desarrollado es más que una simple herramienta de copia; está diseñada para que las comunidades a gran escala puedan resolver sus necesidades de respaldo de servidores, recuperación ante desastres y migración de servidores con un solo clic. ObsCloner puede trasmitir sin problemas miles de canales, jerarquías de roles complejas y emojis personalizados a nuevos servidores sin quedar atrapado en los límites de velocidad de Discord, gracias a sus algoritmos de retraso inteligente.",
      h2: "¿Por qué elegir ObsCloner?",
      li1: "Máxima velocidad y precisión: Utilizando el motor de clonación más optimizado de la industria, transfiere categorías, canales de texto/voz y conjuntos de permisos con un 100% de precisión.",
      li2: "Seguridad de extremo a extremo: Los datos del usuario son sagrados para nosotros. Sus tokens o configuraciones de servidor nunca se almacenan en nuestros servidores; todas las operaciones se comunican directamente con Discord a través de su navegador.",
      li3: "Gestión avanzada de errores: Detecta automáticamente fallos técnicos que puedan ocurrir durante el proceso y garantiza la finalización continuando desde donde se detuvo.",
      li4: "Soporte global: Atendemos a administradores de comunidades de todo el mundo con interfaces y contenidos ofrecidos en 7 idiomas diferentes."
    },
    privacy: {
      title: "Política de Privacidad",
      p1: "Como equipo de ObsCloner, la privacidad y seguridad de sus datos personales son nuestra máxima prioridad. Esta política de privacidad explica en detalle cómo se recopila, utiliza y protege su información cuando utiliza el sitio web y las herramientas de ObsCloner. Al utilizar nuestros servicios, usted acepta las prácticas de datos descritas en esta política.",
      h2_1: "1. Principio de Procesamiento y Almacenamiento de Datos",
      p2: "ObsCloner se basa fundamentalmente en una arquitectura de 'lado del cliente'. Debido a esta arquitectura, los tokens de usuario de Discord, los ID de servidor, las configuraciones de canales u otros metadatos sensibles que ingrese en la aplicación no se transmiten a los servidores de Obsessive Inc., ni se registran ni se almacenan en ninguna base de datos. Todas las llamadas a la API y transferencias de datos se realizan directamente desde su navegador local a los servidores oficiales de la API de Discord a través de un canal cifrado (HTTPS). Esto asegura que usted mantenga el control total sobre sus datos.",
      h2_2: "2. Datos de Registro y Análisis",
      p3: "Cuando visita nuestro sitio, podemos recopilar automáticamente información que su navegador envía. Esta información puede incluir la dirección del Protocolo de Internet (IP) de su dispositivo, el tipo de navegador, la versión del navegador, nuestras páginas que visita, la hora y fecha de su visita, el tiempo dedicado a esas páginas y otros datos estadísticos. Estos datos son completamente anónimos y se utilizan solo para analizar el rendimiento de nuestro sitio web y mejorar la experiencia del usuario.",
      h2_3: "3. Política de Cookies",
      p4: "ObsCloner utiliza cookies para optimizar la experiencia del usuario. Las cookies son pequeños archivos de datos que los sitios web colocan en su dispositivo. Las cookies que utilizamos son principalmente para fines técnicos; por ejemplo, se utilizan para recordar su elección de idioma preferida (ES, EN, etc.) o para asegurar la continuidad de la sesión. Puede rechazar las cookies desde la configuración de su navegador, pero en este caso, tenga en cuenta que algunas funciones de nuestro sitio pueden no funcionar completamente.",
      h2_4: "4. Cumplimiento de GDPR y Protección de Datos",
      p5: "Respetamos los principios del Reglamento General de Protección de Datos de la Unión Europea (GDPR). Nuestros usuarios se reservan el derecho de acceder, corregir o eliminar sus datos. Sin embargo, dado que nuestro sistema no almacena ningún dato personal, no existe un registro de datos que deba ser eliminado. Si tiene alguna pregunta, puede contactarnos en support@aiobsessive.com.",
      h2_5: "5. Enlaces de Terceros",
      p6: "Se utilizan las API de Discord Inc. durante nuestro servicio. Las propias políticas de privacidad y términos de uso de Discord están fuera de nuestro control. Por lo tanto, le recomendamos que revise su documentación oficial para comprender cómo la plataforma Discord procesa sus datos.",
      h2_6: "6. Privacidad de los Niños",
      p7: "Nuestros servicios no se dirigen a niños menores de 13 años. No recopilamos a sabiendas información personal de niños menores de 13 años. Si descubrimos que un niño nos ha proporcionado información personal, eliminamos inmediatamente esta información de nuestros servidores."
    },
    terms: {
      title: "Términos de Servicio",
      p1: "Al acceder al sitio web de ObsCloner y las herramientas que lo acompañan, usted acepta estos términos de servicio, todas las leyes y regulaciones aplicables. Si no está de acuerdo con alguno de estos términos, tiene prohibido utilizar este sitio.",
      h2_1: "1. Licencia y Restricciones de Uso",
      p2: "ObsCloner otorga al usuario una licencia limitada, no transferible y personal para usar la herramienta con el fin de realizar copias de seguridad y migrar servidores de Discord. Bajo esta licencia, usted no puede:\n- Copiar, modificar o realizar ingeniería inversa al software.\n- Usar el software para un propósito comercial o para cualquier exhibición pública.\n- Eliminar cualquier derecho de autor u otras notaciones de propiedad del software.\n- Transferir el software a otra persona o 'reflejarlo' (mirror) en cualquier otro servidor.",
      h2_2: "2. Descargo de Responsabilidad",
      p3: "ObsCloner se proporciona 'tal cual'. Obsessive Inc. no ofrece garantías, expresas o implícitas, con respecto al uso de esta herramienta. Cualquier responsabilidad por el uso de la herramienta de manera contraria a los Términos de Servicio (ToS) de Discord, la copia no autorizada de servidores propiedad de otros o las restricciones de cuenta por parte de Discord recae enteramente en el usuario. Nuestra empresa no se hace responsable de los daños derivados de errores del usuario (ingresar un ID de servidor incorrecto, compartir tokens, etc.) durante el proceso.",
      h2_3: "3. Limitación de Responsabilidad",
      p4: "En ningún caso Obsessive Inc. o sus proveedores serán responsables de ningún daño (incluidos, entre otros, daños por pérdida de datos o ganancias, o debido a la interrupción del negocio) que surjan del uso o la imposibilidad de usar ObsCloner. Debido a que algunas jurisdicciones no permiten limitaciones en las garantías implícitas o limitaciones de responsabilidad por daños consecuentes o incidentales, estas limitaciones pueden no aplicarse a usted.",
      h2_4: "4. Exactitud de los Materiales",
      p5: "Los materiales que aparecen en el sitio podrían incluir errores técnicos, tipográficos o fotográficos. Obsessive Inc. no garantiza que ninguno de los materiales de su sitio web sea exacto, completo o actual. Podemos realizar cambios en los materiales en cualquier momento sin previo aviso.",
      h2_5: "5. Modificaciones a los Términos",
      p6: "Obsessive Inc. puede revisar estos términos de servicio para su sitio web en cualquier momento sin previo aviso. Al utilizar este sitio web, usted acepta estar vinculado por la versión vigente de estos términos de servicio.",
      h2_6: "6. Ley Aplicable",
      p7: "Cualquier reclamo relacionado con ObsCloner se regirá por las leyes de la jurisdicción local sin tener en cuenta su conflicto de disposiciones legales."
    }
  },
  fr: {
    about: {
      title: "À Propos de Nous",
      p1: "ObsCloner est la solution de copie de serveur la plus avancée et la plus fiable du secteur, développée par Obsessive Inc., visant à alléger les charges opérationnelles des gestionnaires de communauté et des propriétaires de serveurs Discord. Fondée en 2026, Obsessive Inc. est une équipe technologique axée sur le développement d'outils d'automatisation innovants pour l'écosystème de l'API Discord, en privilégiant toujours l'expérience utilisateur et la sécurité des données.",
      p2: "Cette plateforme que nous avons développée est plus qu'un simple outil de copie ; elle est conçue pour que les communautés à grande échelle puissent résoudre leurs besoins de sauvegarde de serveur, de reprise après sinistre et de migration de serveur en un seul clic. ObsCloner peut transférer de manière transparente des milliers de salons, des hiérarchies de rôles complexes et des emojis personnalisés vers de nouveaux serveurs sans être bloqué par les limites de débit de Discord, grâce à ses algorithmes de délai intelligents.",
      h2: "Pourquoi choisir ObsCloner ?",
      li1: "Vitesse et précision maximales : en utilisant le moteur de clonage le plus optimisé du secteur, il transfère les catégories, les salons textuels/vocaux et les ensembles de permissions avec une précision de 100 %.",
      li2: "Sécurité de bout en bout : les données des utilisateurs sont sacrées pour nous. Vos jetons ou configurations de serveur ne sont jamais stockés sur nos serveurs ; toutes les opérations communiquent directement avec Discord via votre navigateur.",
      li3: "Gestion avancée des erreurs : il détecte automatiquement les problèmes techniques qui peuvent survenir pendant le processus et garantit la finalisation en reprenant là où il s'était arrêté.",
      li4: "Support mondial : nous répondons aux besoins des gestionnaires de communauté du monde entier avec des interfaces et des contenus proposés en 7 langues différentes."
    },
    privacy: {
      title: "Politique de Confidentialité",
      p1: "En tant qu'équipe d'ObsCloner, la confidentialité et la sécurité de vos données personnelles sont notre priorité absolue. Cette politique de confidentialité explique en détail comment vos informations sont collectées, utilisées et protégées lorsque vous utilisez le site Web et les outils d'ObsCloner. En utilisant nos services, vous consentez aux pratiques en matière de données décrites dans cette politique.",
      h2_1: "1. Principe de Traitement et de Stockage des Données",
      p2: "ObsCloner repose fondamentalement sur une architecture 'côté client'. En raison de cette architecture, les jetons d'utilisateur Discord, les identifiants de serveur, les configurations de salons ou toute autre métadonnée sensible que vous saisissez dans l'application ne sont en aucun cas transmis aux serveurs d'Obsessive Inc., ni enregistrés ou stockés dans une base de données. Tous les appels d'API et transferts de données sont effectués directement de votre navigateur local vers les serveurs d'API officiels de Discord via un canal crypté (HTTPS). Cela garantit que vous conservez un contrôle total sur vos données.",
      h2_2: "2. Données de Journalisation et Analyse",
      p3: "Lorsque vous visitez notre site, nous pouvons collecter automatiquement les informations envoyées par votre navigateur. Ces informations peuvent inclure l'adresse IP (Internet Protocol) de votre appareil, le type de navigateur, la version du navigateur, nos pages que vous visitez, l'heure et la date de votre visite, le temps passé sur ces pages et d'autres données statistiques. Ces données sont totalement anonymes et ne sont utilisées que pour analyser les performances de notre site Web et améliorer l'expérience utilisateur.",
      h2_3: "3. Politique relative aux Cookies",
      p4: "ObsCloner utilise des cookies pour optimiser l'expérience utilisateur. Les cookies sont de petits fichiers de données placés sur votre appareil par les sites Web. Les cookies que nous utilisons sont principalement à des fins techniques ; par exemple, ils sont utilisés pour mémoriser votre choix de langue préféré (FR, EN, etc.) ou pour assurer la continuité de la session. Vous pouvez refuser les cookies dans les paramètres de votre navigateur, mais dans ce cas, veuillez noter que certaines fonctions de notre site peuvent ne pas fonctionner pleinement.",
      h2_4: "4. Conformité au RGPD et Protection des Données",
      p5: "Nous respectons les principes du Règlement général sur la protection des données (RGPD) de l'Union européenne. Nos utilisateurs se réservent le droit d'accéder à leurs données, de les corriger ou de les supprimer. Cependant, comme notre système ne stocke aucune donnée personnelle, il n'existe aucun enregistrement de données à supprimer. Si vous avez des questions, vous pouvez nous contacter à l'adresse support@aiobsessive.com.",
      h2_5: "5. Liens de Tiers",
      p6: "Les API de Discord Inc. sont utilisées dans le cadre de notre service. Les propres politiques de confidentialité et conditions d'utilisation de Discord échappent à notre contrôle. Par conséquent, nous vous recommandons de consulter leur documentation officielle pour comprendre comment la plateforme Discord traite vos données.",
      h2_6: "6. Confidentialité des Enfants",
      p7: "Nos services ne s'adressent pas aux enfants de moins de 13 ans. Nous ne collectons pas sciemment d'informations personnelles auprès d'enfants de moins de 13 ans. Si nous découvrons qu'un enfant nous a fourni des informations personnelles, nous supprimons immédiatement ces informations de nos serveurs."
    },
    terms: {
      title: "Conditions d'Utilisation",
      p1: "En accédant au site Web d'ObsCloner et aux outils qui l'accompagnent, vous acceptez les présentes conditions d'utilisation, toutes les lois et réglementations applicables. Si vous n'êtes pas d'accord avec l'une de ces conditions, il vous est interdit d'utiliser ce site.",
      h2_1: "1. Licence et Restrictions d'Utilisation",
      p2: "ObsCloner accorde à l'utilisateur une licence limitée, non transférable et personnelle d'utilisation de l'outil dans le but de sauvegarder et de migrer des serveurs Discord. Dans le cadre de cette licence, vous ne pouvez pas :\n- Copier, modifier ou désosser le logiciel.\n- Utiliser le logiciel à des fins commerciales ou pour tout affichage public.\n- Supprimer tout droit d'auteur ou autres mentions de propriété du logiciel.\n- Transférer le logiciel à une autre personne ou créer un 'miroir' (mirror) sur un autre serveur.",
      h2_2: "2. Avis de non-responsabilité",
      p3: "ObsCloner est fourni 'en l'état'. Obsessive Inc. ne donne aucune garantie, expresse ou implicite, concernant l'utilisation de cet outil. Toute responsabilité pour l'utilisation de l'outil d'une manière contraire aux conditions d'utilisation de Discord (ToS), la copie non autorisée de serveurs appartenant à autrui ou les restrictions de compte par Discord incombe entièrement à l'utilisateur. Notre société ne peut être tenue responsable des dommages résultant d'erreurs de l'utilisateur (saisie d'un identifiant de serveur incorrect, partage de jetons, etc.) pendant le processus.",
      h2_3: "3. Limitation de Responsabilité",
      p4: "En aucun cas Obsessive Inc. ou sus fournisseurs ne seront responsables de tout dommage (y compris, sans limitation, les dommages pour perte de données ou de profit, ou dus à une interruption d'activité) découlant de l'utilisation ou de l'incapacité d'utiliser ObsCloner. Étant donné que certaines juridictions n'autorisent pas de limitations sur les garanties implicites, ou des limitations de responsabilité pour les dommages consécutifs ou accessoires, ces limitations peuvent ne pas s'appliquer à vous.",
      h2_4: "4. Exactitude des Matériaux",
      p5: "Les documents apparaissant sur le site peuvent comporter des erreurs techniques, typographiques ou photographiques. Obsessive Inc. ne garantit pas que les documents de son site Web sont exacts, complets ou à jour. Nous pouvons apporter des modifications aux documents à tout moment et sans préavis.",
      h2_5: "5. Modifications des Conditions",
      p6: "Obsessive Inc. peut réviser les présentes conditions d'utilisation de son site Web à tout moment et sans préavis. En utilisant ce site Web, vous acceptez d'être lié par la version alors en vigueur de ces conditions d'utilisation.",
      h2_6: "6. Droit Applicable",
      p7: "Toute réclamation relative à ObsCloner sera régie par les lois de la juridiction locale, sans égard à ses dispositions en matière de conflit de lois."
    }
  },
  de: {
    about: {
      title: "Über Uns",
      p1: "ObsCloner ist die branchenweit fortschrittlichste und zuverlässigste Server-Kopierlösung, die unter Obsessive Inc. entwickelt wurde. Sie zielt darauf ab, die betriebliche Belastung von Discord-Community-Managern und Serverbesitzern zu verringern. Obsessive Inc. wurde 2026 gegründet und ist ein Technologie-Team, das sich auf die Entwicklung innovativer Automatisierungstools für das Discord-API-Ökosystem konzentriert, wobei Benutzererfahrung und Datensicherheit stets im Vordergrund stehen.",
      p2: "Diese von uns entwickelte Plattform ist mehr als nur ein einfaches Kopier-Tool. Sie wurde so konzipiert, dass große Communities ihre Anforderungen an Server-Backup, Disaster Recovery und Server-Migration mit einem einzigen Klick lösen können. Dank seiner intelligenten Verzögerungsalgorithmen kann ObsCloner Tausende von Kanälen, komplexe Rollenhierarchien und benutzerdefinierte Emojis nahtlos auf neue Server übertragen, ohne von den Ratenlimits von Discord blockiert zu werden.",
      h2: "Warum ObsCloner wählen?",
      li1: "Maximale Geschwindigkeit und Präzision: Durch die Verwendung der optimiertesten Klon-Engine der Branche werden Kategorien, Text-/Sprachkanäle und Berechtigungssätze mit 100 % Genauigkeit übertragen.",
      li2: "Ende-zu-Ende-Sicherheit: Benutzerdaten sind für uns heilig. Ihre Token oder Serverkonfigurationen werden niemals auf unseren Servern gespeichert; alle Vorgänge kommunizieren über Ihren Browser direkt mit Discord.",
      li3: "Erweiterte Fehlerbehandlung: Technische Fehler, die während des Prozesses auftreten können, werden automatisch erkannt und die Fertigstellung wird garantiert, indem der Vorgang an der Stelle fortgesetzt wird, an der er unterbrochen wurde.",
      li4: "Globaler Support: Wir bedienen Community-Manager weltweit mit Benutzeroberflächen und Inhalten, die in 7 verschiedenen Sprachen angeboten werden."
    },
    privacy: {
      title: "Datenschutzerklärung",
      p1: "Als Team von ObsCloner hat die Privatsphäre und Sicherheit Ihrer persönlichen Daten für uns höchste Priorität. Diese Datenschutzrichtlinie erklärt im Detail, wie Ihre Informationen bei der Nutzung der ObsCloner-Website und -Tools gesammelt, verwendet und geschützt werden. Durch die Nutzung unserer Dienste stimmen Sie den in dieser Richtlinie beschriebenen Datenpraktiken zu.",
      h2_1: "1. Prinzip der Datenverarbeitung und -speicherung",
      p2: "ObsCloner basiert grundlegend auf einer 'Client-Side'-Architektur. Aufgrund dieser Architektur werden Discord-Benutzer-Token, Server-IDs, Kanalkonfigurationen oder andere sensible Metadaten, die Sie in die Anwendung eingeben, in keiner Weise an die Server von Obsessive Inc. übermittelt, aufgezeichnet oder in einer Datenbank gespeichert. Alle API-Aufrufe und Datenübertragungen erfolgen direkt von Ihrem lokalen Browser über einen verschlüsselten Kanal (HTTPS) an die offiziellen API-Server von Discord. Dies stellt sicher, dass Sie die volle Kontrolle über Ihre Daten behalten.",
      h2_2: "2. Protokolldaten und Analysen",
      p3: "Wenn Sie unsere Website besuchen, erfassen wir möglicherweise automatisch Informationen, die Ihr Browser sendet. Diese Informationen können die Internetprotokoll-Adresse (IP-Adresse) Ihres Geräts, den Browsertyp, die Browserversion, unsere von Ihnen besuchten Seiten, die Uhrzeit und das Datum Ihres Besuchs, die auf diesen Seiten verbrachte Zeit und andere statistische Daten umfassen. Diese Daten ist vollständig anonym und werden nur verwendet, um die Leistung unserer Website zu analysieren und das Benutzererlebnis zu verbessern.",
      h2_3: "3. Cookie-Richtlinie",
      p4: "ObsCloner verwendet Cookies, um das Benutzererlebnis zu optimieren. Cookies sind kleine Datendateien, die von Websites auf Ihrem Gerät abgelegt werden. Die von uns verwendeten Cookies dienen primär technischen Zwecken; sie werden beispielsweise verwendet, um Ihre bevorzugte Sprachwahl (DE, EN usw.) zu speichern oder um die Kontinuität der Sitzung zu gewährleisten. Sie können Cookies in Ihren Browsereinstellungen ablehnen, beachten Sie jedoch in diesem Fall, dass einige Funktionen unserer Website möglicherweise nicht vollständig funktionieren.",
      h2_4: "4. GDPR- und Datenschutz-Konformität",
      p5: "Wir respektieren die Grundsätze der Datenschutz-Grundverordnung der Europäischen Union (GDPR). Unsere Nutzer behalten sich das Recht vor, auf ihre Daten zuzugreifen, diese zu korrigieren oder zu löschen. Da unser System jedoch keine personenbezogenen Daten speichert, gibt es keinen Datensatz, der gelöscht werden müsste. Wenn Sie Fragen haben, können Sie uns unter support@aiobsessive.com kontaktieren.",
      h2_5: "5. Links von Drittanbietern",
      p6: "Während unseres Dienstes werden die APIs von Discord Inc. verwendet. Die eigenen Datenschutzrichtlinien und Nutzungsbedingungen von Discord liegen außerhalb unserer Kontrolle. Wir empfehlen Ihnen daher, deren offizielle Dokumentation zu lesen, um zu verstehen, wie die Discord-Plattform Ihre Daten verarbeitet.",
      h2_6: "6. Privatsphäre von Kindern",
      p7: "Unsere Dienste richten sich nicht an Kinder unter 13 Jahren. Wir sammeln wissentlich keine personenbezogenen Daten von Kindern unter 13 Jahren. Wenn wir feststellen, dass ein Kind uns personenbezogene Daten bereitgestellt hat, löschen wir diese Daten umgehend von unseren Servern."
    },
    terms: {
      title: "Nutzungsbedingungen",
      p1: "Durch den Zugriff auf die ObsCloner-Website und die dazugehörigen Tools erklären Sie sich mit diesen Nutzungsbedingungen sowie allen geltenden Gesetzen und Vorschriften einverstanden. Wenn Sie mit einer dieser Bedingungen nicht einverstanden sind, ist Ihnen die Nutzung dieser Website untersagt.",
      h2_1: "1. Lizenz- und Nutzungsbeschränkungen",
      p2: "ObsCloner gewährt dem Nutzer eine begrenzte, nicht übertragbare und persönliche Lizenz zur Nutzung des Tools zum Sichern und Migrieren von Discord-Servern. Im Rahmen dieser Lizenz dürfen Sie nicht:\n- Die Software kopieren, modifizieren oder zurückentwickeln (Reverse Engineering).\n- Die Software für kommerzielle Zwecke oder für eine öffentliche Präsentation verwenden.\n- Urheberrechtsvermerke oder andere Eigentumshinweise von der Software entfernen.\n- Die Software an eine andere Person übertragen oder auf einem anderen Server 'spiegeln' (mirror).",
      h2_2: "2. Haftungsausschluss (Disclaimer)",
      p3: "ObsCloner wird 'wie besehen' zur Verfügung gestellt. Obsessive Inc. übernimmt keine ausdrücklichen oder stillschweigenden Garantien bezüglich der Nutzung dieses Tools. Jegliche Verantwortung für die Nutzung des Tools in einer Weise, die gegen die Discord-Nutzungsbedingungen (ToS) verstößt, das unbefugte Kopieren von Servern Dritter oder Kontobeschränkungen durch Discord liegt allein beim Nutzer. Unser Unternehmen kann nicht für Schäden haftbar gemacht werden, die durch Benutzerfehler (Eingabe einer falschen Server-ID, Weitergabe von Token usw.) während des Prozesses entstehen.",
      h2_3: "3. Haftungsbeschränkung",
      p4: "In keinem Fall haften Obsessive Inc. oder seine Lieferanten für Schäden (einschließlich, aber nicht beschränkt auf Schäden aus Daten- oder Gewinnverlust oder aufgrund von Betriebsunterbrechungen), die aus der Nutzung oder Unfähigkeit zur Nutzung von ObsCloner entstehen. Da einige Gerichtsbarkeiten keine Einschränkungen stillschweigender Garantien oder Haftungsbeschränkungen für Folgeschäden oder zufällige Schäden zulassen, gelten diese Einschränkungen möglicherweise nicht für Sie.",
      h2_4: "4. Genauigkeit der Materialien",
      p5: "Die auf der Website erscheinenden Materialien können technische, typografische oder fotografische Fehler enthalten. Obsessive Inc. garantiert nicht, dass die Materialien auf seiner Website korrekt, vollständig oder aktuell sind. Wir können jederzeit ohne Vorankündigung Änderungen an den Materialien vornehmen.",
      h2_5: "5. Änderungen der Bedingungen",
      p6: "Obsessive Inc. kann diese Nutzungsbedingungen für seine Website jederzeit ohne Vorankündigung überarbeiten. Durch die Nutzung dieser Website erklären Sie sich mit der jeweils aktuellen Version dieser Nutzungsbedingungen einverstanden.",
      h2_6: "6. Anwendbares Recht",
      p7: "Alle Ansprüche im Zusammenhang mit ObsCloner unterliegen den Gesetzen der örtlichen Gerichtsbarkeit, ungeachtet der Bestimmungen des Kollisionsrechts."
    }
  },
  pt: {
    about: {
      title: "Sobre Nós",
      p1: "O ObsCloner é a solução de cópia de servidor mais avançada e confiável do setor, desenvolvida pela Obsessive Inc., com o objetivo de aliviar as cargas operacionais dos gestores de comunidades e proprietários de servidores do Discord. Fundada em 2026, a Obsessive Inc. é uma equipe tecnológica focada no desenvolvimento de ferramentas de automação inovadoras para o ecossistema da API do Discord, priorizando sempre a experiência do usuário e a segurança dos dados.",
      p2: "Esta plataforma que desenvolvemos é mais do que apenas uma simples ferramenta de cópia; foi projetada para que comunidades de grande escala possam resolver as suas necessidades de backup de servidor, recuperação de desastres e migração de servidor com um único clique. O ObsCloner pode transferir perfeitamente milhares de canais, hierarquias de cargos complexas e emojis personalizados para novos servidores sem ficar retido nos limites de taxa do Discord, graças aos seus algoritmos de atraso inteligente.",
      h2: "Por que escolher o ObsCloner?",
      li1: "Velocidade e precisão máximas: Usando o mecanismo de clonagem mais otimizado do setor, transfere categorias, canais de texto/voz e conjuntos de permissões com 100% de precisão.",
      li2: "Segurança de ponta a ponta: Os dados do usuário são sagrados para nós. Os seus tokens ou configurações de servidor nunca são armazenados nos nossos servidores; todas as operações comunicam diretamente com o Discord através do seu navegador.",
      li3: "Gestão avançada de erros: Deteta automaticamente falhas técnicas que possam ocorrer durante o processo e garante a conclusão continuando a partir de onde parou.",
      li4: "Suporte global: Atendemos a gestores de comunidades em todo o mundo com interfaces e conteúdos oferecidos em 7 idiomas diferentes."
    },
    privacy: {
      title: "Política de Privacidade",
      p1: "Como equipe do ObsCloner, a privacidade e a segurança dos seus dados pessoais são a nossa maior prioridade. Esta política de privacidade explica detalhadamente como as suas informações são coletadas, usadas e protegidas quando você usa o site e as ferramentas do ObsCloner. Ao usar os nossos serviços, você concorda com as práticas de dados descritas nesta política.",
      h2_1: "1. Princípio de Processamento e Armazenamento de Dados",
      p2: "O ObsCloner é fundamentalmente construído sobre uma arquitetura 'client-side'. Devido a esta arquitetura, os tokens de usuário do Discord, IDs de servidor, configurações de canais ou outros metadados confidenciais que você insere na aplicação não são transmitidos aos servidores da Obsessive Inc., nem registrados ou armazenados em qualquer base de dados. Todas as chamadas de API e transferências de dados são feitas diretamente do seu navegador local para os servidores oficiais de API do Discord através de um canal criptografado (HTTPS). Isso garante que você mantenha o controle total sobre os seus dados.",
      h2_2: "2. Dados de Registro e Analítica",
      p3: "Quando você visita o nosso site, podemos coletar automaticamente informações que o seu navegador envia. Essas informações podem incluir o endereço IP (Internet Protocol) do seu dispositivo, o tipo de navegador, a versão do navegador, as nossas páginas que você visita, a hora e data da sua visita, o tempo gasto nessas páginas e outros dados estatísticos. Esses dados são completamente anônimos e são usados apenas para analisar o desempenho do nosso site e melhorar a experiência do usuário.",
      h2_3: "3. Política de Cookies",
      p4: "O ObsCloner usa cookies para otimizar a experiência do usuário. Cookies são pequenos arquivos de dados colocados no seu dispositivo pelos sites. Os cookies que usamos são principalmente para fins técnicos; por exemplo, são usados para lembrar a sua escolha de idioma preferida (PT, EN, etc.) ou para garantir a continuidade da sessão. Você pode recusar cookies nas configurações do seu navegador, mas, neste caso, observe que algumas funções do nosso site podem não funcionar totalmente.",
      h2_4: "4. Conformidade com o RGPD e Proteção de Dados",
      p5: "Respeitamos os princípios do Regulamento Geral de Proteção de Dados da União Europa (RGPD). Os nossos usuários reservam-se o direito de acessar, corrigir ou excluir os seus dados. No entanto, como o nosso sistema não armazena nenhum dado pessoal, não há registro de dados a ser excluído. Se você tiver alguma dúvida, pode contactar-nos em support@aiobsessive.com.",
      h2_5: "5. Links de Terceiros",
      p6: "As APIs da Discord Inc. são usadas durante o nosso serviço. As próprias políticas de privacidade e termos de uso do Discord estão fora do nosso controle. Portanto, recomendamos que você analise a documentação oficial deles para entender como a plataforma Discord processa os seus dados.",
      h2_6: "6. Privacidade de Crianças",
      p7: "Os nossos serviços não se destinam a crianças menores de 13 anos. Não coletamos conscientemente informações pessoais de crianças menores de 13 anos. Se descobrirmos que uma criança nos forneceu informações pessoais, excluímos imediatamente essas informações dos nossos servidores."
    },
    terms: {
      title: "Termos de Serviço",
      p1: "Ao acessar o site do ObsCloner e as ferramentas que o acompanham, você concorda com estes termos de serviço, todas as leis e regulamentos aplicáveis. Se você não concordar com qualquer um desses termos, você está proibido de usar este site.",
      h2_1: "1. Licença e Restrições de Uso",
      p2: "O ObsCloner concede ao usuário uma licença limitada, não transferível e pessoal para usar a ferramenta com o propósito de fazer backup e migrar servidores do Discord. Sob esta licença, você não pode:\n- Copiar, modificar ou fazer engenharia reversa do software.\n- Usar o software para um propósito comercial ou para qualquer exibição pública.\n- Remover quaisquer direitos autorais ou outras notações de propriedade do software.\n- Transferir o software para outra pessoa ou 'espelhar' (mirror) em qualquer outro servidor.",
      h2_2: "2. Isenção de Responsabilidade",
      p3: "O ObsCloner é fornecido 'tal como está'. A Obsessive Inc. não oferece garantias, expressas ou implícitas, em relação ao uso desta ferramenta. Qualquer responsabilidade pelo uso da ferramenta de forma contrária aos Termos de Serviço (ToS) do Discord, cópia não autorizada de servidores pertencentes a terceiros ou restrições de conta pelo Discord cabe inteiramente ao usuário. A nossa empresa não pode ser responsabilizada por danos decorrentes de erros do usuário (inserir ID de servidor incorreto, partilhar tokens, etc.) durante o processo.",
      h2_3: "3. Limitação de Responsabilidade",
      p4: "Em nenhum caso a Obsessive Inc. ou os seus fornecedores serão responsáveis por quaisquer danos (incluindo, sem limitação, danos por perda de dados ou lucro, ou devido à interrupção dos negócios) decorrentes do uso ou da impossibilidade de usar o ObsCloner. Como algumas jurisdições não permitem limitações em garantias implícitas ou limitações de responsabilidade por danos consequentes ou incidentais, essas limitações podem não se aplicar a você.",
      h2_4: "4. Precisão dos Materiais",
      p5: "Os materiais que aparecem no site podem incluir erros técnicos, tipográficos ou fotográficos. A Obsessive Inc. não garante que qualquer um dos materiais no seu site seja preciso, completo ou atual. Podemos fazer alterações nos materiais a qualquer momento, sem aviso prévio.",
      h2_5: "5. Modificações nos Termos",
      p6: "A Obsessive Inc. pode revisar estes termos de serviço para o seu site a qualquer momento, sem aviso prévio. Ao usar este site, você concorda em ficar vinculado à versão atual desses termos de serviço.",
      h2_6: "6. Lei Aplicável",
      p7: "Qualquer reclamação relativa ao ObsCloner será regida pelas leis da jurisdição local, sem considerar o seu conflito de disposições legais."
    }
  },
  it: {
    about: {
      title: "Chi Siamo",
      p1: "ObsCloner è la soluzione di copia dei server più avanzata e affidabile del settore, sviluppata da Obsessive Inc., con l'obiettivo di alleggerire il carico operativo dei gestori di comunità Discord e dei proprietari di server. Fondata nel 2026, Obsessive Inc. è un team tecnologico focalizzato sullo sviluppo di strumenti di automazione innovativi per l'ecosistema delle API di Discord, dando sempre priorità all'esperienza dell'utente e alla sicurezza dei dati.",
      p2: "Questa piattaforma che abbiamo sviluppato è molto più di un semplice strumento di copia; è progettata affinché le comunità su larga scala possano risolvere le loro esigenze di backup dei server, disaster recovery e migrazione dei server con un singolo clic. ObsCloner può trasferire senza problemi migliaia di canali, gerarchie di ruoli complesse ed emoji personalizzate su nuovi server senza essere bloccato dai limiti di frequenza di Discord, grazie ai suoi algoritmi di ritardo intelligente.",
      h2: "Perché scegliere ObsCloner?",
      li1: "Massima velocità e precisione: Utilizzando il motore di clonazione più ottimizzato del settore, trasferisce categorie, canali testuali/vocali e set di permessi con una precisione del 100%.",
      li2: "Sicurezza end-to-end: I dati degli utenti sono sacri per noi. I tuoi token o le configurazioni del server non vengono mai memorizzati sui nostri server; tutte le operazioni comunicano direttamente con Discord tramite il tuo browser.",
      li3: "Gestione avanzata degli errori: Rileva automaticamente i problemi tecnici che possono verificarsi durante il processo e garantisce il completamento continuando da dove era stato interrotto.",
      li4: "Supporto globale: Ci rivolgiamo ai gestori di comunità in tutto il mondo con interfacce e contenuti offerti in 7 lingue diverse."
    },
    privacy: {
      title: "Informativa sulla Privacy",
      p1: "Come team di ObsCloner, la privacy e la sicurezza dei tuoi dati personali sono la nostra massima priorità. Questa informativa sulla privacy spiega in dettaglio come le tue informazioni vengono raccolte, utilizzate e protette quando utilizzi il sito web e gli strumenti di ObsCloner. Utilizzando i nostri servizi, acconsenti alle pratiche relative ai dati descritte in questa informativa.",
      h2_1: "1. Principio di Trattamento e Conservazione dei Dati",
      p2: "ObsCloner è fondamentalmente costruito su un'architettura 'lato client'. A causa di questa architettura, i token utente Discord, gli ID server o altre informazioni sensibili inserite nell'applicazione non vengono trasmessi ai server di Obsessive Inc. né memorizzati nei nostri database in alcun modo. Tutte le chiamate API e i trasferimenti di dati vengono effettuati direttamente dal tuo browser locale ai server API ufficiali di Discord tramite un canale crittografato (HTTPS). Ciò garantisce di mantenere il pieno controllo sui propri dati.",
      h2_2: "2. Dati di Log e Analisi",
      p3: "Quando visiti il nostro sito, potremmo raccogliere automaticamente le informazioni inviate dal tuo browser. Queste informazioni possono includere l'indirizzo IP (Internet Protocol) del dispositivo, il tipo di browser, la versione del browser, le nostre pagine visitate, l'ora e la data della visita, il tempo trascorso su tali pagine e altri dati statistici. Questi dati sono completamente anonimi e vengono utilizzati solo per analizzare le prestazioni del nostro sito web e migliorare l'esperienza dell'utente.",
      h2_3: "3. Politica sui Cookie",
      p4: "ObsCloner utilizza i cookie per ottimizzare l'esperienza dell'utente. I cookie sono piccoli file di dati inseriti nel dispositivo dai siti web. I cookie che utilizziamo sono principalmente per scopi tecnici; ad esempio, vengono utilizzati per ricordare la scelta della lingua preferita (IT, EN, ecc.) o per garantire la continuità della sessione. Puoi rifiutare i cookie dalle impostazioni del browser, ma in questo caso, tieni presente che alcune funzioni del nostro sito potrebbero non funzionare completamente.",
      h2_4: "4. Conformità GDPR e Protezione dei Dati",
      p5: "Rispettiamo i principi del Regolamento Generale sulla Protezione dei Dati dell'Unione Europea (GDPR). I nostri utenti si riservano il diritto di accedere, correggere o cancellare i propri dati. Tuttavia, poiché il nostro sistema non memorizza alcun dato personale, non esiste alcun record di dati da cancellare. In caso di domande, puoi contattarci all'indirizzo support@aiobsessive.com.",
      h2_5: "5. Collegamenti di Terze Parti",
      p6: "Le API di Discord Inc. vengono utilizzate durante il nostro servizio. Le informative sulla privacy e i termini d'uso di Discord sono al di fuori del nostro controllo. Pertanto, ti consigliamo di consultare la loro documentazione ufficiale per capire come la piattaforma Discord elabora i tuoi dati.",
      h2_6: "6. Privacy dei Minori",
      p7: "I nostri servizi non si rivolgono a bambini di età inferiore ai 13 anni. Non raccogliamo consapevolmente informazioni personali da bambini di età inferiore ai 13 anni. Se scopriamo che un bambino ci ha fornito informazioni personali, provvederemo immediatamente a cancellare tali informazioni dai nostri server."
    },
    terms: {
      title: "Termini di Servizio",
      p1: "Accedendo al sito web di ObsCloner e agli strumenti di accompagnamento, accetti i presenti termini di servizio, tutte le leggi e i regolamenti applicabili. Se non sei d'accordo con uno qualsiasi di questi termini, ti è vietato utilizzare questo sito.",
      h2_1: "1. Licenza e Restrizioni d'Uso",
      p2: "ObsCloner concede all'utente una licenza limitata, non trasferibile e personale per l'utilizzo dello strumento allo scopo di eseguire il backup e la migrazione dei server Discord. Sotto questa licenza, non puoi:\n- Copiare, modificare o decodificare il software.\n- Utilizzare il software per scopi commerciali o per qualsiasi esposizione pubblica.\n- Rimuovere qualsiasi copyright o altre indicazioni di proprietà dal software.\n- Trasferire il software a un'altra persona o creare un 'mirror' su qualsiasi altro server.",
      h2_2: "2. Dichiarazione di non responsabilità",
      p3: "ObsCloner viene fornito 'così com'è'. Obsessive Inc. non fornisce alcuna garanzia, espressa o implicita, in merito all'uso di questo strumento. Qualsiasi responsabilità per l'utilizzo dello strumento in modo contrario ai Termini di Servizio (ToS) di Discord, la copia non autorizzata di server di proprietà di terzi o le restrizioni dell'account da parte di Discord ricade interamente sull'utente. La nostra azienda non può essere ritenuta responsabile per danni derivanti da errori dell'utente (inserimento di ID server errato, condivisione di token, ecc.) durante il processo.",
      h2_3: "3. Limitazione di Responsabilità",
      p4: "In nessun caso Obsessive Inc. o i suoi fornitori saranno responsabili per eventuali danni (inclusi, a titolo esemplificativo, danni per perdita di dati o profitto, o dovuti a interruzione dell'attività) derivanti dall'uso o dall'impossibilità di utilizzare ObsCloner. Poiché alcune giurisdizioni non consentono limitazioni alle garanzie implicite o limitazioni di responsabilità per danni consequenziali o incidentali, tali limitazioni potrebbero non essere applicabili.",
      h2_4: "4. Accuratezza dei Materiali",
      p5: "I materiali che appaiono sul sito potrebbero includere errori tecnici, tipografici o fotografici. Obsessive Inc. non garantisce che i materiali sul suo sito web siano accurati, completi o aggiornati. Possiamo apportare modifiche ai materiali in qualsiasi momento senza preavviso.",
      h2_5: "5. Modifiche ai Termini",
      p6: "Obsessive Inc. può rivedere i presenti termini di servizio per il proprio sito web in qualsiasi momento senza preavviso. Utilizzando questo sito web, accetti di essere vincolato dalla versione corrente di questi termini di servizio.",
      h2_6: "6. Legge Applicabile",
      p7: "Qualsiasi reclamo relativo a ObsCloner sarà regolato dalle leggi della giurisdizione locale senza riguardo al suo conflitto di disposizioni di legge."
    }
  },
  ru: {
    about: {
      title: "О нас",
      p1: "ObsCloner — это самое передовое и надежное в отрасли решение для копирования серверов, разработанное в рамках Obsessive Inc. и направленное на облегчение операционной нагрузки администраторов сообществ Discord и владельцев серверов. Компания Obsessive Inc., основанная в 2026 году, представляет собой технологическую команду, ориентированную на разработку инновационных инструментов автоматизации для экосистемы Discord API, всегда уделяя приоритетное внимание пользовательскому опыту и безопасности данных.",
      p2: "Платформа, которую мы разработали, — это больше, чем просто инструмент для копирования; она разработана для того, чтобы крупные сообщества могли решать свои задачи по резервному копированию серверов, аварийному восстановлению и миграции серверов одним щелчком мыши. ObsCloner может беспрепятственно переносить тысячи каналов, сложные иерархии ролей и пользовательские эмодзи на новые серверы, не попадая под ограничения скорости Discord, благодаря своим алгоритмам интеллектуальной задержки.",
      h2: "Почему стоит выбрать ObsCloner?",
      li1: "Максимальная скорость и точность: используя самый оптимизированный движок клонирования в отрасли, он переносит категории, текстовые/голосовые каналы и наборы разрешений со 100% точностью.",
      li2: "Сквозная безопасность: пользовательские данные для нас священны. Ваши токены или конфигурации серверов никогда не сохраняются на наших серверах; все операции взаимодействуют напрямую с Discord через ваш браузер.",
      li3: "Расширенная обработка ошибок: система автоматически обнаруживает технические сбои, которые могут возникнуть в процессе, и обеспечивает завершение, продолжая с того места, где остановилась.",
      li4: "Глобальная поддержка: мы обслуживаем администраторов сообществ по всему миру, предлагая интерфейс и контент на 7 различных языках."
    },
    privacy: {
      title: "Политика конфиденциальности",
      p1: "Для команды ObsCloner конфиденциальность и безопасность ваших персональных данных являются нашим главным приоритетом. Настоящая политика конфиденциальности подробно объясняет, как ваша информация собирается, используется и защищается при использовании веб-сайта и инструментов ObsCloner. Используя наши услуги, вы соглашаетесь с практикой обработки данных, описанной в настоящей политике.",
      h2_1: "1. Принцип обработки и хранения данных",
      p2: "ObsCloner фундаментально построен на клиентской архитектуре. Благодаря этой архитектуре пользовательские токены Discord, идентификаторы серверов, конфигурации каналов или другие конфиденциальные метаданные, которые вы вводите в приложение, никоим образом не передаются на серверы Obsessive Inc., не записываются и не хранятся в какой-либо базе данных. Все вызовы API и передача данных осуществляются напрямую из вашего локального браузера на официальные серверы API Discord через зашифрованный канал (HTTPS). Это гарантирует, что вы сохраняете полный контроль над своими данными.",
      h2_2: "2. Данные журнала и аналитика",
      p3: "Когда вы посещаете наш сайт, мы можем автоматически собирать информацию, которую отправляет ваш браузер. Эта информация может включать IP-адрес вашего устройства, тип браузера, версию браузера, посещаемые вами страницы нашего сайта, время и дату вашего посещения, время, проведенное на этих страницах, и другие статистические данные. Эти данные полностью анонимны и используются только для анализа производительности нашего веб-сайта и улучшения пользовательского опыта.",
      h2_3: "3. Политика использования файлов cookie",
      p4: "ObsCloner использует файлы cookie для оптимизации пользовательского опыта. Файлы cookie — это небольшие файлы данных, размещаемые веб-сайтами на вашем устройстве. Файлы cookie, которые мы используем, предназначены в первую очередь для технических целей; например, они используются для запоминания выбранного вами языка (RU, EN и т. д.) или для обеспечения непрерывности сеанса. Вы можете отказаться от использования файлов cookie в настройках своего браузера, но в этом случае учтите, что некоторые функции нашего сайта могут работать не в полной мере.",
      h2_4: "4. Соответствие GDPR и защита данных",
      p5: "Мы соблюдаем принципы Общего регламента по защите данных Европейского Союза (GDPR). Наши пользователи сохраняют за собой право на доступ к своим данным, их исправление или удаление. Однако, поскольку наша система не хранит никаких персональных данных, записи данных для удаления не существует. Если у вас есть вопросы, вы можете связаться с нами по адресу support@aiobsessive.com.",
      h2_5: "5. Сторонние ссылки",
      p6: "В процессе предоставления наших услуг используются API Discord Inc. Собственная политика конфиденциальности и условия использования Discord находятся вне нашего контроля. Поэтому мы рекомендуем вам ознакомиться с их официальной документацией, чтобы понять, как платформа Discord обрабатывает ваши данные.",
      h2_6: "6. Конфиденциальность детей",
      p7: "Наши услуги не предназначены для детей младше 13 лет. Мы сознательно не собираем личную информацию от детей младше 13 лет. Если мы обнаружим, что ребенок предоставил нам личную информацию, мы немедленно удалим эту информацию с наших серверов."
    },
    terms: {
      title: "Условия использования",
      p1: "Заходя на веб-сайт ObsCloner и используя сопутствующие инструменты, вы соглашаетесь с настоящими условиями обслуживания, всеми применимыми законами и правилами. Если вы не согласны с каким-либо из этих условий, вам запрещено использовать этот сайт.",
      h2_1: "1. Лицензия и ограничения на использование",
      p2: "ObsCloner предоставляет пользователю ограниченную, непередаваемую и персональную лицензию на использование инструмента для целей резервного копирования и миграции серверов Discord. По этой лицензии вы не имеете права:\n- Копировать, изменять или реконструировать программное обеспечение.\n- Использовать программное обеспечение в коммерческих целях или для любого публичного показа.\n- Удалять любые авторские права или другие проприетарные обозначения из программного обеспечения.\n- Передавать программное обеспечение другому лицу или «зеркалировать» его на любом другом сервере.",
      h2_2: "2. Отказ от ответственности",
      p3: "ObsCloner предоставляется «как есть». Obsessive Inc. не дает никаких гарантий, явных или подразумеваемых, в отношении использования этого инструмента. Любая ответственность за использование инструмента способом, противоречащим Условиям обслуживания Discord (ToS), несанкционированное копирование серверов, принадлежащих другим лицам, или ограничения учетной записи со стороны Discord лежит исключительно на пользователе. Наша компания не несет ответственности за ущерб, возникший в результате ошибок пользователя (ввод неверного ID сервера, передача токенов и т. д.) в ходе процесса.",
      h2_3: "3. Ограничение ответственности",
      p4: "Ни при каких обстоятельствах компания Obsessive Inc. или ее поставщики не несут ответственности за любой ущерб (включая, помимо прочего, ущерб в связи с потерей данных или прибыли или из-за прерывания деловой активности), возникающий в результате использования или невозможности использования ObsCloner. Поскольку некоторые юрисдикции не допускают ограничений на подразумеваемые гарантии или ограничений ответственности за косвенный или случайный ущерб, эти ограничения могут к вам не применяться.",
      h2_4: "4. Точность материалов",
      p5: "Материалы, размещенные на сайте, могут содержать технические, типографские или фотографические ошибки. Obsessive Inc. не гарантирует, что любые материалы на веб-сайте являются точными, полными или актуальными. Мы можем вносить изменения в материалы в любое время без предварительного уведомления.",
      h2_5: "5. Изменения условий",
      p6: "Obsessive Inc. может пересматривать настоящие условия обслуживания для своего веб-сайта в любое время без предварительного уведомления. Используя этот веб-сайт, вы соглашаетесь соблюдать текущую версию настоящих условий обслуживания.",
      h2_6: "6. Применимое право",
      p7: "Любые претензии, связанные с ObsCloner, регулируются законами местной юрисдикции без учета положений о конфликте законов."
    }
  },
  ja: {
    about: {
      title: "私たちについて",
      p1: "ObsCloner は、Obsessive Inc. の下で開発された業界で最も先進的で信頼性の高いサーバー コピー ソリューションであり、Discord コミュニティ マネージャーやサーバー所有者の運用の負担を軽減することを目的としています。2026 年に設立された Obsessive Inc. は、Discord API エコシステム向けの革新的な自動化ツールの開発に注力しているテクノロジー チームであり、常にユーザー エクスペリエンスとデータのセキュリティを最優先しています。",
      p2: "私たちが開発したこのプラットフォームは、単なるコピー ツールではありません。大規模なコミュニティがサーバーのバックアップ、災害復旧、サーバーの移行に関するニーズをシングル クリックで解決できるように設計されています。ObsCloner は、スマート ディレイ アルゴリズムのおかげで、Discord のレート制限に捕まることなく、何千ものチャンネル、複雑なロール階層、カスタム絵文字を新しいサーバーにシームレスに転送できます。",
      h2: "ObsCloner を選ぶ理由",
      li1: "最大限のスピードと精度: 業界で最も最適化されたクローン エンジンを使用して、カテゴリ、テキスト/ボイス チャンネル、権限セットを 100% の精度で転送します。",
      li2: "エンドツーエンドのセキュリティ: ユーザー データは私たちにとって神聖なものです。トークンやサーバー構成が私たちのサーバーに保存されることはありません。すべての操作は、ブラウザを介して Discord と直接通信します。",
      li3: "高度なエラー処理: プロセス中に発生する可能性のある技術的な不具合を自動的に検出し、中断したところから再開することで完了を保証します。",
      li4: "グローバル サポート: 7 つの異なる言語で提供されるインターフェイスとコンテンツにより、世界中のコミュニティ マネージャーに対応しています。"
    },
    privacy: {
      title: "プライバシー ポリシー",
      p1: "ObsCloner チームとして、お客様の個人データのプライバシーとセキュリティは私たちの最優先事項です。このプライバシー ポリシーでは、ObsCloner のウェブサイトとツールを使用する際にお客様の情報がどのように収集、使用、保護されるかについて詳しく説明します。当社のサービスを使用することにより、お客様はこのポリシーに記載されているデータの取り扱いに同意したものとみなされます。",
      h2_1: "1. データの処理と保存の原則",
      p2: "ObsCloner は根本的に「クライアント側」のアーキテクチャに基づいています。このアーキテクチャにより、アプリケーションに入力した Discord ユーザー トークン、サーバー ID、チャンネル構成、またはその他の機密性の高いメタデータが Obsessive Inc. サーバーに送信されたり、記録されたり、データベースに保存されたりすることはありません。すべての API 呼び出しとデータ転送は、暗号化されたチャネル (HTTPS) を介して、ローカル ブラウザから Discord の公式 API サーバーに直接行われます。これにより、お客様はデータを完全に制御できます。",
      h2_2: "2. ログ データと分析",
      p3: "当社のサイトにアクセスすると、ブラウザが送信する情報が自動的に収集される場合があります。この情報には、デバイスのインターネット プロトコル (IP) アドレス、ブラウザの種類、ブラウザのバージョン、アクセスした当社のページ、アクセスの日時、それらのページで費やした時間、およびその他の統計データが含まれる場合があります。このデータは完全に匿名であり、当社のウェブサイトのパフォーマンスを分析し、ユーザー エクスペリエンスを向上させるためにのみ使用されます。",
      h2_3: "3. クッキー ポリシー",
      p4: "ObsCloner は、ユーザー エクスペリエンスを最適化するためにクッキーを使用します。クッキーは、ウェブサイトによってデバイスに配置される小さなデータ ファイルです。当社が使用するクッキーは主に技術的な目的のためのものです。たとえば、選択した言語設定 (JA、EN など) を記憶したり、セッションの継続性を確保したりするために使用されます。ブラウザの設定からクッキーを拒否できますが、その場合、当社のサイトの一部の機能が完全に動作しない可能性があることに注意してください。",
      h2_4: "4. GDPR およびデータ保護の遵守",
      p5: "私たちは、欧州連合の一般データ保護規則 (GDPR) の原則を尊重します。当社のユーザーは、自らのデータにアクセス、修正、または削除する権利を留保します。ただし、当社のシステムは個人データを保存しないため、削除するデータ レコードは存在しません。ご不明な点がございましたら、support@aiobsessive.com までお問い合わせください。",
      h2_5: "5. サードパーティ リンク",
      p6: "当社のサービス中に Discord Inc. の API が使用されます。Discord 独自のプライバシー ポリシーと利用規約は当社の制御の及ばないものです。したがって、Discord プラットフォームがお客様のデータをどのように処理するかを理解するために、彼らの公式ドキュメントを確認することをお勧めします。",
      h2_6: "6. お子様のプライバシー",
      p7: "当社のサービスは 13 歳未満のお子様を対象としていません。13 歳未満のお子様から意図的に個人情報を収集することはありません。お子様が当社に個人情報を提供したことが判明した場合、当社はその情報を直ちにサーバーから削除します。"
    },
    terms: {
      title: "利用規約",
      p1: "ObsCloner のウェブサイトおよび付属のツールにアクセスすることにより、お客様はこれらの利用規約、適用されるすべての法律および規制に同意したものとみなされます。これらの規約のいずれかに同意しない場合は、このサイトの使用を禁止します。",
      h2_1: "1. ライセンスと使用制限",
      p2: "ObsCloner は、ユーザーに対し、Discord サーバーのバックアップおよび移行を目的として、このツールを使用するための限定的で譲渡不可能な個人的なライセンスを付与します。このライセンスに基づき、お客様は以下のことを行うことはできません。\n- ソフトウェアをコピー、修正、またはリバース エンジニアリングすること。\n- 商業目的または公開展示のためにソフトウェアを使用すること。\n- ソフトウェアから著作権またはその他の所有権の表記を削除すること。\n- ソフトウェアを別の人に転送したり、他のサーバーで「ミラーリング」したりすること。",
      h2_2: "2. 免責事項",
      p3: "ObsCloner は「現状有姿」で提供されます。Obsessive Inc. は、このツールの使用に関して、明示または黙示を問わず、いかなる保証も行いません。Discord の利用規約 (ToS) に反する形でのツールの使用、他人が所有するサーバーの不正コピー、または Discord によるアカウント制限に関する責任はすべてユーザーにあります。当社は、プロセス中のユーザー エラー (誤ったサーバー ID の入力、トークンの共有など) から生じる損害について責任を負いません。",
      h2_3: "3. 責任の制限",
      p4: "いかなる場合においても、Obsessive Inc. またはそのサプライヤーは、ObsCloner の使用または使用不能から生じるいかなる損害 (データの損失、利益の損失、または事業の中断による損害を含みますが、これらに限定されません) についても責任を負いません。一部の法域では、黙示の保証の制限、または結果的損害もしくは付随的損害に対する責任の制限が認められていないため、これらの制限がお客様に適用されない場合があります。",
      h2_4: "4. 資料の正確性",
      p5: "サイトに掲載されている資料には、技術的、誤植的、または写真的な誤りが含まれている可能性があります。Obsessive Inc. は、ウェブサイト上の資料が正確、完全、または最新であることを保証しません。当社は、予告なしにいつでも資料を変更することがあります。",
      h2_5: "5. 規約の変更",
      p6: "Obsessive Inc. は、予告なしにいつでもウェブサイトの利用規約を改訂することがあります。このウェブサイトを使用することにより、お客様はその時点の最新バージョンの利用規約に拘束されることに同意したものとみなされます。",
      h2_6: "6. 準拠法",
      p7: "ObsCloner に関するいかなる請求も、抵触法の規定にかかわらず、所在地の法律に準拠するものとします。"
    }
  },
  ar: {
    about: {
      title: "من نحن",
      p1: "ObsCloner هو الحل الأكثر تقدماً وموثوقية في الصناعة لنسخ الخوادم، تم تطويره تحت مظلة Obsessive Inc.، ويهدف إلى تخفيف الأعباء التشغيلية لمديري مجتمعات ديسكورد وأصحاب الخوادم. تأسست Obsessive Inc. في عام 2026، وهي فريق تقني يركز على تطوير أدوات أتمتة مبتكرة لمنظومة Discord API، مع إعطاء الأولوية دائماً لتجربة المستخدم وأمن البيانات.",
      p2: "المنصة التي طورناها هي أكثر من مجرد أداة نسخ بسيطة؛ فقد صُممت لتمكين المجتمعات واسعة النطاق من حل احتياجات النسخ الاحتياطي للخوادم، والتعافي من الكوارث، وهجرة الخوادم بنقرة واحدة. يمكن لـ ObsCloner نقل آلاف القنوات، والتسلسلات الهرمية المعقدة للأدوار، والرموز التعبيرية المخصصة إلى خوادم جديدة بسلاسة دون الوقوع في قيود معدل ديسكورد (Rate Limits)، بفضل خوارزميات التأخير الذكية.",
      h2: "لماذا تختار ObsCloner؟",
      li1: "أقصى سرعة ودقة: باستخدام محرك النسخ الأكثر تحسيناً في الصناعة، يقوم بنقل الفئات، وقنوات النص/الصوت، ومجموعات الأذونات بدقة 100%.",
      li2: "أمن شامل: بيانات المستخدم مقدسة بالنسبة لنا. لا يتم تخزين الرموز (Tokens) أو تكوينات الخادم الخاصة بك على خوادمنا أبداً؛ جميع العمليات تتواصل مباشرة مع ديسكورد عبر متصفحك.",
      li3: "معالجة متقدمة للأخطاء: يكتشف تلقائياً المشكلات الفنية التي قد تحدث أثناء العملية ويضمن اكتمالها من خلال الاستمرار من حيث توقفت.",
      li4: "دعم عالمي: نحن نخدم مديري المجتمعات في جميع أنحاء العالم من خلال واجهات ومحتوى متوفر بـ 7 لغات مختلفة."
    },
    privacy: {
      title: "سياسة الخصوصية",
      p1: "بصفتنا فريق ObsCloner، فإن خصوصية وأمن بياناتك الشخصية هي أولويتنا القصوى. توضح سياسة الخصوصية هذه بالتفصيل كيفية جمع معلوماتك واستخدامها وحمايتها عند استخدام موقع وأدوات ObsCloner. باستخدام خدماتنا، فإنك توافق على ممارسات البيانات الموضحة في هذه السياسة.",
      h2_1: "1. مبدأ معالجة البيانات وتخزينها",
      p2: "يعتمد ObsCloner بشكل أساسي على بنية 'جانب العميل' (client-side). وبسبب هذه البنية، فإن رموز مستخدم ديسكورد، أو معرفات الخادم، أو تكوينات القنوات، أو غيرها من البيانات الوصفية الحساسة التي تدخلها في التطبيق لا يتم إرسالها إلى خوادم Obsessive Inc.، ولا يتم تسجيلها أو تخزينها في أي قاعدة بيانات. يتم إجراء جميع استدعاءات API ونقل البيانات مباشرة من متصفحك المحلي إلى خوادم API الرسمية لديسكورد عبر قناة مشفرة (HTTPS). يضمن ذلك احتفاظك بالتحكم الكامل في بياناتك.",
      h2_2: "2. بيانات السجل والتحليلات",
      p3: "عند زيارة موقعنا، قد نجمع تلقائياً المعلومات التي يرسلها متصفحك. قد تتضمن هذه المعلومات عنوان بروتوكول الإنترنت (IP) لجهازك، ونوع المتصفح، وإصداره، والصفحات التي تزورها في موقعنا، ووقت وتاريخ زيارتك، والوقت الذي تقضيه في تلك الصفحات، وغيرها من البيانات الإحصائية. هذه البيانات مجهولة تماماً وتُستخدم فقط لتحليل أداء موقعنا وتحسين تجربة المستخدم.",
      h2_3: "3. سياسة ملفات تعريف الارتباط (Cookies)",
      p4: "يستخدم ObsCloner ملفات تعريف الارتباط لتحسين تجربة المستخدم. ملفات تعريف الارتباط هي ملفات بيانات صغيرة تضعها المواقع على جهازك. ملفات تعريف الارتباط التي نستخدمها هي للأغراض الفنية بشكل أساسي؛ على سبيل المثال، تُستخدم لتذكر اختيارك للغة المفضلة (AR، EN، إلخ) أو لضمان استمرارية الجلسة. يمكنك رفض ملفات تعريف الارتباط من إعدادات متصفحك، ولكن في هذه الحالة، يرجى ملاحظة أن بعض وظائف موقعنا قد لا تعمل بشكل كامل.",
      h2_4: "4. الامتثال للائحة العامة لحماية البيانات (GDPR)",
      p5: "نحن نحترم مبادئ اللائحة العامة لحماية البيانات للاتحاد الأوروبي (GDPR). يحفظ مستخدمونا الحق في الوصول إلى بياناتهم أو تصحيحها أو حذفها. ومع ذلك، نظراً لأن نظامنا لا يخزن أي بيانات شخصية، فلا يوجد سجل بيانات ليتم حذفه. إذا كان لديك أي أسئلة، يمكنك التواصل معنا عبر support@aiobsessive.com.",
      h2_5: "5. روابط الجهات الخارجية",
      p6: "تُستخدم واجهات برمجة تطبيقات Discord Inc. أثناء تقديم خدمتنا. سياسات الخصوصية وشروط الاستخدام الخاصة بديسكورد خارجة عن سيطرتنا. لذلك، نوصيك بمراجعة وثائقهم الرسمية لفهم كيفية معالجة منصة ديسكورد لبياناتك.",
      h2_6: "6. خصوصية الأطفال",
      p7: "خدماتنا لا تستهدف الأطفال دون سن 13 عاماً. نحن لا نجمع معلومات شخصية عن قصد من الأطفال دون سن 13 عاماً. إذا اكتشفنا أن طفلاً قد زودنا بمعلومات شخصية، فسنقوم بحذف هذه المعلومات فوراً من خوادمنا."
    },
    terms: {
      title: "شروط الخدمة",
      p1: "من خلال الوصول إلى موقع ObsCloner والأدوات المرفقة به، فإنك توافق على شروط الخدمة هذه، وجميع القوانين واللوائح المعمول بها. إذا كنت لا توافق على أي من هذه الشروط، فيُحظر عليك استخدام هذا الموقع.",
      h2_1: "1. ترخيص وقيود الاستخدام",
      p2: "يمنح ObsCloner المستخدم ترخيصاً محدوداً وغير قابل للتحويل وشخصياً لاستخدام الأداة لغرض النسخ الاحتياطي وهجرة خوادم ديسكورد. بموجب هذا الترخيص، لا يجوز لك:\n- نسخ البرنامج أو تعديله أو عكس هندسته.\n- استخدام البرنامج لأي غرض تجاري أو للعرض العام.\n- إزالة أي حقوق نشر أو إشعارات ملكية أخرى من البرنامج.\n- نقل البرنامج إلى شخص آخر أو 'عكسه' (mirror) على أي خادم آخر.",
      h2_2: "2. إخلاء المسؤولية",
      p3: "يتم تقديم ObsCloner 'كما هو'. لا تقدم Obsessive Inc. أي ضمانات، صريحة أو ضمنية، فيما يتعلق باستخدام هذه الأداة. تقع أي مسؤولية عن استخدام الأداة بطريقة تتعارض مع شروط خدمة ديسكورد (ToS)، أو النسخ غير المصرح به للخوادم المملوكة للآخرين، أو قيود الحساب من قبل ديسكورد، على عاتق المستخدم بالكامل. لا يمكن تحميل شركتنا المسؤولية عن الأضرار الناشئة عن أخطاء المستخدم (إدخال معرف خادم غير صحيح، مشاركة الرموز، إلخ) أثناء العملية.",
      h2_3: "3. تحديد المسؤولية",
      p4: "في أي حال من الأحوال، لن تكون Obsessive Inc. أو موردوها مسؤولين عن أي أضرار (بما في ذلك، على سبيل المثال لا الحصر، الأضرار الناجمة عن فقدان البيانات أو الربح، أو بسبب توقف العمل) تنشأ عن استخدام أو عدم القدرة على استخدام ObsCloner. ونظراً لأن بعض الولايات القضائية لا تسمح بفرض قيود على الضمانات الضمنية، أو تحديد المسؤولية عن الأضرار التبعية أو العرضية، فقد لا تنطبق هذه القيود عليك.",
      h2_4: "4. دقة المواد",
      p5: "قد تتضمن المواد التي تظهر على الموقع أخطاء فنية أو مطبعية أو فوتوغرافية. لا تضمن Obsessive Inc. أن أي من المواد الموجودة على موقعها دقيقة أو كاملة أو حديثة. قد نجري تغييرات على المواد في أي وقت دون إشعار مسبق.",
      h2_5: "5. التعديلات على الشروط",
      p6: "قد تقوم Obsessive Inc. بمراجعة شروط الخدمة هذه لموقعها في أي وقت دون إشعار مسبق. باستخدام هذا الموقع، فإنك توافق على الالتزام بالإصدار الحالي من شروط الخدمة هذه.",
      h2_6: "6. القانون الحاكم",
      p7: "تخضع أي مطالبة تتعلق بـ ObsCloner لقوانين الولاية القضائية المحلية دون اعتبار لتعارضها مع نصوص القوانين."
    }
  },
  id: {
    about: {
      title: "Tentang Kami",
      p1: "ObsCloner adalah solusi penyalinan server tercanggih dan terandal di industri yang dikembangkan di bawah Obsessive Inc., yang bertujuan untuk meringankan beban operasional manajer komunitas Discord dan pemilik server. Didirikan pada tahun 2026, Obsessive Inc. adalah tim teknologi yang berfokus pada pengembangan alat otomatisasi inovatif untuk ekosistem Discord API, dengan selalu memprioritaskan pengalaman pengguna dan keamanan data.",
      p2: "Platform yang kami kembangkan ini lebih dari sekadar alat penyalin sederhana; platform ini dirancang agar komunitas skala besar dapat menyelesaikan kebutuhan pencadangan server, pemulihan bencana, dan migrasi server mereka dengan satu klik. ObsCloner dapat mentransfer ribuan saluran, hierarki peran yang kompleks, dan emoji khusus ke server baru dengan mulus tanpa tertangkap oleh batas kecepatan Discord, berkat algoritme penundaan cerdasnya.",
      h2: "Mengapa Memilih ObsCloner?",
      li1: "Kecepatan dan Presisi Maksimum: Menggunakan mesin kloning paling optimal di industri, platform ini mentransfer kategori, saluran teks/suara, dan set izin dengan akurasi 100%.",
      li2: "Keamanan End-to-End: Data pengguna sangat berharga bagi kami. Token atau konfigurasi server Anda tidak pernah disimpan di server kami; semua operasi berkomunikasi langsung dengan Discord melalui peramban Anda.",
      li3: "Penanganan Kesalahan Tingkat Lanjut: Platform ini secara otomatis mendeteksi gangguan teknis yang mungkin terjadi selama proses dan memastikan penyelesaian dengan melanjutkan dari tempat terakhirnya.",
      li4: "Dukungan Global: Kami melayani manajer komunitas di seluruh dunia dengan antarmuka dan konten yang ditawarkan dalam 7 bahasa berbeda."
    },
    privacy: {
      title: "Kebijakan Privasi",
      p1: "Sebagai tim ObsCloner, privasi dan keamanan data pribadi Anda adalah prioritas utama kami. Kebijakan privasi ini menjelaskan secara rinci bagaimana informasi Anda dikumpulkan, digunakan, dan dilindungi saat Anda menggunakan situs web dan alat ObsCloner. Dengan menggunakan layanan kami, Anda menyetujui praktik data yang dijelaskan dalam kebijakan ini.",
      h2_1: "1. Prinsip Pemrosesan dan Penyimpanan Data",
      p2: "ObsCloner secara fundamental dibangun di atas arsitektur 'client-side'. Karena arsitektur ini, token pengguna Discord, ID server, konfigurasi saluran, atau metadata sensitif lainnya yang Anda masukkan ke dalam aplikasi tidak dikirimkan ke server Obsessive Inc., dicatat, atau disimpan dalam basis data apa pun. Semua panggilan API dan transfer data dilakukan langsung dari peramban lokal Anda ke server API resmi Discord melalui saluran terenkripsi (HTTPS). Hal ini memastikan bahwa Anda memegang kendali penuh atas data Anda.",
      h2_2: "2. Data Log dan Analitik",
      p3: "Saat Anda mengunjungi situs kami, kami dapat secara otomatis mengumpulkan informasi yang dikirimkan peramban Anda. Informasi ini dapat mencakup alamat Protokol Internet (IP) perangkat Anda, jenis peramban, versi peramban, halaman situs kami yang Anda kunjungi, waktu dan tanggal kunjungan Anda, waktu yang dihabiskan di halaman tersebut, dan data statistik lainnya. Data ini sepenuhnya anonim dan hanya digunakan untuk menganalisis kinerja situs web kami dan meningkatkan pengalaman pengguna.",
      h2_3: "3. Kebijakan Cookie",
      p4: "ObsCloner menggunakan cookie untuk mengoptimalkan pengalaman pengguna. Cookie adalah file data kecil yang ditempatkan di perangkat Anda oleh situs web. Cookie yang kami gunakan terutama untuk tujuan teknis; misalnya, digunakan untuk mengingat pilihan bahasa pilihan Anda (ID, EN, dll.) atau untuk memastikan kelangsungan sesi. Anda dapat menolak cookie dari pengaturan peramban Anda, tetapi dalam hal ini, harap dicatat bahwa beberapa fungsi situs kami mungkin tidak berfungsi sepenuhnya.",
      h2_4: "4. Kepatuhan GDPR dan Perlindungan Data",
      p5: "Kami menghormati prinsip-prinsip Peraturan Perlindungan Data Umum Uni Eropa (GDPR). Pengguna kami berhak mengakses, memperbaiki, atau menghapus data mereka. Namun, karena sistem kami tidak menyimpan data pribadi apa pun, tidak ada catatan data yang harus dihapus. Jika Anda memiliki pertanyaan, Anda dapat menghubungi kami di support@aiobsessive.com.",
      h2_5: "5. Tautan Pihak Ketiga",
      p6: "API Discord Inc. digunakan selama layanan kami. Kebijakan privasi dan ketentuan penggunaan Discord sendiri berada di luar kendali kami. Oleh karena itu, kami menyarankan agar Anda meninjau dokumentasi resmi mereka untuk memahami bagaimana platform Discord memproses data Anda.",
      h2_6: "6. Privasi Anak-anak",
      p7: "Layanan kami tidak ditujukan untuk anak-anak di bawah usia 13 tahun. Kami tidak secara sengaja mengumpulkan informasi pribadi dari anak-anak di bawah 13 tahun. Jika kami menemukan bahwa seorang anak telah memberikan informasi pribadi kepada kami, kami akan segera menghapus informasi tersebut dari server kami."
    },
    terms: {
      title: "Ketentuan Layanan",
      p1: "Dengan mengakses situs web ObsCloner dan alat yang menyertainya, Anda setuju dengan ketentuan layanan ini, semua hukum dan peraturan yang berlaku. Jika Anda tidak setuju dengan salah satu ketentuan ini, Anda dilarang menggunakan situs ini.",
      h2_1: "1. Lisensi dan Batasan Penggunaan",
      p2: "ObsCloner memberi pengguna lisensi terbatas, tidak dapat dialihkan, dan pribadi untuk menggunakan alat tersebut untuk tujuan mencadangkan dan memigrasikan server Discord. Di bawah lisensi ini, Anda tidak boleh:\n- Menyalin, memodifikasi, atau merekayasa balik perangkat lunak.\n- Menggunakan perangkat lunak untuk tujuan komersial atau untuk tampilan publik apa pun.\n- Menghapus hak cipta atau notasi kepemilikan lainnya dari perangkat lunak.\n- Mentransfer perangkat lunak ke orang lain atau 'mencerminkannya' (mirror) di server lain mana pun.",
      h2_2: "2. Penafian",
      p3: "ObsCloner disediakan 'apa adanya'. Obsessive Inc. tidak memberikan jaminan, baik tersurat maupun tersirat, mengenai penggunaan alat ini. Tanggung jawab apa pun atas penggunaan alat dengan cara yang bertentangan dengan Ketentuan Layanan Discord (ToS), penyalinan server milik orang lain yang tidak sah, atau pembatasan akun oleh Discord sepenuhnya berada di tangan pengguna. Perusahaan kami tidak dapat bertanggung jawab atas kerusakan yang timbul dari kesalahan pengguna (memasukkan ID server yang salah, membagikan token, dll.) selama proses berlangsung.",
      h2_3: "3. Batasan Tanggung Jawab",
      p4: "Dalam keadaan apa pun Obsessive Inc. atau pemasoknya tidak bertanggung jawab atas kerusakan apa pun (termasuk, tanpa batasan, kerusakan karena hilangnya data atau keuntungan, atau karena gangguan bisnis) yang timbul dari penggunaan atau ketidakmampuan untuk menggunakan ObsCloner. Karena beberapa yurisdiksi tidak mengizinkan batasan pada jaminan tersirat, atau batasan tanggung jawab untuk kerusakan konsekuensial o insidental, batasan ini mungkin tidak berlaku untuk Anda.",
      h2_4: "4. Keakuratan Materi",
      p5: "Materi yang muncul di situs dapat mencakup kesalahan teknis, tipografi, atau fotografi. Obsessive Inc. tidak menjamin bahwa materi apa pun di situs webnya akurat, lengkap, oder terkini. Kami dapat membuat perubahan pada materi kapan saja tanpa pemberitahuan.",
      h2_5: "5. Modifikasi Ketentuan",
      p6: "Obsessive Inc. dapat merevisi ketentuan layanan ini untuk situs webnya kapan saja tanpa pemberitahuan. Dengan menggunakan situs web ini, Anda setuju untuk terikat oleh versi ketentuan layanan yang berlaku saat itu.",
      h2_6: "6. Hukum yang Mengatur",
      p7: "Setiap klaim yang berkaitan dengan ObsCloner akan diatur oleh hukum yurisdiksi lokal tanpa memperhatikan pertentangan ketentuan hukumnya."
    }
  }
};
